### ISSUE TITLE
Translation to MoXI in JSON format fails for several SMV models

### ISSUE THREAD

**Issue by nianzelee** [ModelChecker/moxi-mc-flow#10]
- Environment: Ubuntu 22.04, Linux 6.5.0-41-generic, Python 3.10.12
- Commit: 6240207d1ae5629751b15ccddba97b2021e8d7f7
- Command: `python3 translate.py test/smv/QF_ABV/FIFOs.smv moxi-json --output FIFOs.json --validate`
- Expected output: A MoXI model `FIFOs.json` in JSON format
- Actual output:

```
translate.py: ERROR: json2moxi.py: ERROR: JSON failed validation against schema 'identifier' is a required property

Failed validating 'required' in schema[7]['properties']['init']['properties']['args']['items']:
    {'$id': 'expr.json',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     'additionalProperties': False,
     'description': 'MoXI Expressions',
     'properties': {'args': {'items': {'$ref': 'expr.json'},
                             'type': 'array'},
                    'identifier': {'oneOf': [{'type': 'string'},
                                             {'type': 'integer'},
                                             {'$ref': 'identifier.json'}]}},
     'required': ['identifier'],
     'title': 'Expression',
     'type': 'object'}

On instance['init']['args'][2]:
    {}
sortcheck.py: ERROR: Failed parsing
```

Dropping `--validate` made the command finish without errors, but the produced JSON file seems wrong. Cf. [FIFOs.json](https://github.com/user-attachments/files/15970493/FIFOs.json)

The translation to JSON also failed for other SMV models, e.g., `test/smv/QF_BV/adding.1.prop1-back-serstep.btor.smv`.

**Comment by cgjohannsen** [comment]
Thanks for the bug report! The JSON schema needs to be updated to support let bindings, which I will fix ASAP.

**Comment by cgjohannsen** [comment]
Tracking in #11
