### ISSUE TITLE
Array constant's shape information missing in MoXI-JSON

### ISSUE THREAD

**Issue by Po-Chun-Chien** [ModelChecker/moxi-mc-flow#14]
I tried to translate `benchmarks/vis/arrays/am2910_p1.smv` into MoXI and MoXI-JSON (commit 6240207).

The `init` formula in MoXI looks like:

```
:init (and (= _dquote_a9_dquote_ ((as const (Array (_ BitVec 3) (_ BitVec 12))) #b000000000000)) (let ((__expr1 (= _dquote__dollar_auto_dollar_rename_dot_cc_colon_157_colon_execute_dollar_305_dquote_ #b000000000000))) (let ((__expr2 (= _dquote__dollar_auto_dollar_rename_dot_cc_colon_157_colon_execute_dollar_293_dquote_ #b000000000000))) (let ((__expr3 (= _dquote__dollar_auto_dollar_rename_dot_cc_colon_157_colon_execute_dollar_303_dquote_ #b000))) (let ((__expr4 (and __expr3 __expr2))) (let ((__expr5 (and __expr4 __expr1))) __expr5)))))) 
```

And the `init` formula in MoXI-JSON looks like:

```
"init": {"identifier": {"symbol": "and", "indices": []}, "args": [{"identifier": {"symbol": "=", "indices": []}, "args": [{"identifier": "_dquote_a9_dquote_"}, {"identifier": {"symbol": "const", "indices": []}, "args": [{"identifier": "#b000000000000"}]}]}, {}]}
```

The missing support for let bindings is already known (tracked in #11).
However, the size of the array constant is missing in MoXI-JSON.

- in MoXI: `((as const (Array (_ BitVec 3) (_ BitVec 12)))`
- in MoXI-JSON: `{"identifier": {"symbol": "const", "indices": []}, "args": [{"identifier": "#b000000000000"}]}`

Should its identifier contain such information?
Otherwise, as a user of MoXI-JSON, how could the size be determined?

**Comment by cgjohannsen** [comment]
Thanks for the report. Tracking in #16
